# -*- coding: utf-8 -*-
# Copyright (c) 2025, BrainWise and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class OfflineInvoiceSync(Document):
    """
    Tracks offline invoice synchronization to prevent duplicate submissions.

    Each record maps an offline_id (generated client-side) to a Sales Invoice,
    allowing the system to detect and prevent duplicate sync attempts.
    """

    def before_insert(self):
        """Set synced_at timestamp before insert."""
        if not self.synced_at:
            self.synced_at = frappe.utils.now_datetime()

    @staticmethod
    def create_sync_record(offline_id, sales_invoice, pos_profile=None, customer=None):
        """
        Create a sync record for an offline invoice.

        Args:
            offline_id: The unique offline ID generated by the client
            sales_invoice: The Sales Invoice name created on the server
            pos_profile: Optional POS Profile name
            customer: Optional Customer name

        Returns:
            The created OfflineInvoiceSync document or existing one if duplicate
        """
        if not offline_id or not sales_invoice:
            return None

        # Check if record already exists
        existing = frappe.db.get_value(
            "Offline Invoice Sync",
            {"offline_id": offline_id},
            "name"
        )
        if existing:
            return frappe.get_doc("Offline Invoice Sync", existing)

        doc = frappe.get_doc({
            "doctype": "Offline Invoice Sync",
            "offline_id": offline_id,
            "sales_invoice": sales_invoice,
            "pos_profile": pos_profile,
            "customer": customer,
        })
        doc.flags.ignore_permissions = True
        doc.insert()
        return doc

    @staticmethod
    def is_synced(offline_id):
        """
        Check if an offline_id has already been synced.

        Args:
            offline_id: The offline ID to check

        Returns:
            dict with 'synced' (bool) and 'sales_invoice' (str or None)
        """
        if not offline_id:
            return {"synced": False, "sales_invoice": None}

        existing = frappe.db.get_value(
            "Offline Invoice Sync",
            {"offline_id": offline_id},
            ["name", "sales_invoice"],
            as_dict=True
        )

        if existing:
            return {"synced": True, "sales_invoice": existing.sales_invoice}

        return {"synced": False, "sales_invoice": None}
